[workspace.metadata.dylint]
libraries = [
    { git = "https://github.com/KSXGitHub/perfectionist", tag = "0.0.0-rc.14" },
]

["perfectionist::derive_ordering"]
style = "prefix_then_alphabetical"
prefix = [
    "Debug", "Display", "Error",
    "Default", "SmartDefault",
    "Clone", "Copy",
    "PartialEq", "Eq", "PartialOrd", "Ord",
    "Hash",
    "AsRef", "AsMut", "Deref", "DerefMut",
    "From", "Into", "TryFrom", "TryInto", "FromStr",
    "IntoIterator",
    "Add", "AddAssign", "Sub", "SubAssign", "Mul", "MulAssign", "Div", "DivAssign",
    "Sum", "Product",
    "LowerHex", "UpperHex", "Octal",
]

["perfectionist::macro_argument_binding"]
deny_extra = ["debug_assert_op", "debug_assert_op_expr"]

["perfectionist::single_letter_closure_param"]
extra_trivial_callback_methods = ["sort_reflection_by"]
