[workspace.metadata.dylint]
libraries = [
    { git = "https://github.com/KSXGitHub/perfectionist", rev = "892533129e44ef48f7be468a9804ff36325f70fa" },
]

["perfectionist::derive_ordering"]
style = "prefix_then_alphabetical"
prefix = [
    "Debug", "Display", "Error",
    "Default", "SmartDefault",
    "Clone", "Copy",
    "PartialEq", "Eq", "PartialOrd", "Ord",
    "Hash",
    "AsRef", "AsMut", "Deref", "DerefMut",
    "From", "Into", "TryFrom", "TryInto", "FromStr",
    "IntoIterator",
    "Add", "AddAssign", "Sub", "SubAssign", "Mul", "MulAssign", "Div", "DivAssign",
    "Sum", "Product",
    "LowerHex", "UpperHex", "Octal",
]

["perfectionist::macro_argument_binding"]
deny_extra = ["debug_assert_op", "debug_assert_op_expr"]
allow_extra = ["bump", "link", "symlink", "test_case", "visualize"]

["perfectionist::single_letter_closure_param"]
comparison_methods = ["sort_by", "sort_unstable_by", "sort_by_key", "sort_unstable_by_key", "min_by", "max_by", "min_by_key", "max_by_key", "binary_search_by", "binary_search_by_key", "cmp_by", "partial_cmp_by", "eq_by", "fold", "sort_reflection_by", "into_sorted_by"]
