.TH pdu 1 "pdu 0.21.1"
.SH NAME
pdu \- Summarize disk usage of the set of files, recursively for directories.
.SH SYNOPSIS
\fBpdu\fR [\fB\-\-json\-input\fR] [\fB\-\-json\-output\fR] [\fB\-b\fR|\fB\-\-bytes\-format\fR \fIBYTES_FORMAT\fR] [\fB\-H\fR|\fB\-\-deduplicate\-hardlinks\fR] [\fB\-x\fR|\fB\-\-one\-file\-system\fR] [\fB\-\-top\-down\fR] [\fB\-\-align\-right\fR] [\fB\-q\fR|\fB\-\-quantity\fR \fIQUANTITY\fR] [\fB\-d\fR|\fB\-\-max\-depth\fR \fIMAX_DEPTH\fR] [\fB\-w\fR|\fB\-\-total\-width\fR \fITOTAL_WIDTH\fR] [\fB\-\-column\-width\fR \fITREE_WIDTH\fR \fIBAR_WIDTH\fR] [\fB\-m\fR|\fB\-\-min\-ratio\fR \fIMIN_RATIO\fR] [\fB\-\-no\-sort\fR] [\fB\-s\fR|\fB\-\-silent\-errors\fR] [\fB\-p\fR|\fB\-\-progress\fR] [\fB\-\-threads\fR \fITHREADS\fR] [\fB\-\-omit\-json\-shared\-details\fR] [\fB\-\-omit\-json\-shared\-summary\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIFILES\fR]
.SH DESCRIPTION
Summarize disk usage of the set of files, recursively for directories.
.PP
Copyright: Apache\-2.0 © 2021 Hoàng Văn Khải <https://github.com/KSXGitHub/>
.br
Sponsor: https://github.com/sponsors/KSXGitHub
.SH OPTIONS
.TP
[\fIFILES\fR]
List of files and/or directories
.TP
\fB\-\-json\-input\fR
Read JSON data from stdin
.RS
.PP
Cannot be used with \fB\-\-deduplicate\-hardlinks\fR, \fB\-\-one\-file\-system\fR, \fB\-\-quantity\fR.
.RE
.TP
\fB\-\-json\-output\fR
Print JSON data instead of an ASCII chart
.TP
\fB\-b\fR, \fB\-\-bytes\-format\fR \fI<BYTES_FORMAT>\fR [default: metric]
How to display the numbers of bytes
.RS
.TP
\fB\-\-bytes\-format plain\fR
Display plain number of bytes without units
.TP
\fB\-\-bytes\-format metric\fR
Use metric scale, i.e. 1K = 1000B, 1M = 1000K, and so on
.TP
\fB\-\-bytes\-format binary\fR
Use binary scale, i.e. 1K = 1024B, 1M = 1024K, and so on
.RE
.TP
\fB\-H\fR, \fB\-\-deduplicate\-hardlinks\fR, \fB\-\-detect\-links\fR, \fB\-\-dedupe\-links\fR
Detect and subtract the sizes of hardlinks from their parent directory totals
.RS
.PP
Cannot be used with \fB\-\-json\-input\fR.
.RE
.TP
\fB\-x\fR, \fB\-\-one\-file\-system\fR
Skip directories on different filesystems
.RS
.PP
Cannot be used with \fB\-\-json\-input\fR.
.RE
.TP
\fB\-\-top\-down\fR
Print the tree top\-down instead of bottom\-up
.TP
\fB\-\-align\-right\fR
Set the root of the bars to the right
.TP
\fB\-q\fR, \fB\-\-quantity\fR \fI<QUANTITY>\fR [default: block-size]
Aspect of the files/directories to be measured
.RS
.TP
\fB\-\-quantity apparent\-size\fR
Measure apparent sizes
.TP
\fB\-\-quantity block\-size\fR
Measure block sizes (block\-count * 512B)
.TP
\fB\-\-quantity block\-count\fR
Count numbers of blocks
.RE
.RS
.PP
Cannot be used with \fB\-\-json\-input\fR.
.RE
.TP
\fB\-d\fR, \fB\-\-max\-depth\fR, \fB\-\-depth\fR \fI<MAX_DEPTH>\fR [default: 10]
Maximum depth to display the data. Could be either "inf" or a positive integer
.TP
\fB\-w\fR, \fB\-\-total\-width\fR, \fB\-\-width\fR \fI<TOTAL_WIDTH>\fR
Width of the visualization
.RS
.PP
Cannot be used with \fB\-\-column\-width\fR.
.RE
.TP
\fB\-\-column\-width\fR \fI<TREE_WIDTH>\fR \fI<BAR_WIDTH>\fR
Maximum widths of the tree column and width of the bar column
.RS
.PP
Cannot be used with \fB\-\-total\-width\fR.
.RE
.TP
\fB\-m\fR, \fB\-\-min\-ratio\fR \fI<MIN_RATIO>\fR [default: 0.01]
Minimal size proportion required to appear
.TP
\fB\-\-no\-sort\fR
Do not sort the branches in the tree
.TP
\fB\-s\fR, \fB\-\-silent\-errors\fR, \fB\-\-no\-errors\fR
Prevent filesystem error messages from appearing in stderr
.TP
\fB\-p\fR, \fB\-\-progress\fR
Report progress being made at the expense of performance
.TP
\fB\-\-threads\fR \fI<THREADS>\fR [default: auto]
Set the maximum number of threads to spawn. Could be either "auto", "max", or a positive integer
.TP
\fB\-\-omit\-json\-shared\-details\fR
Do not output `.shared.details` in the JSON output
.TP
\fB\-\-omit\-json\-shared\-summary\fR
Do not output `.shared.summary` in the JSON output
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with '\-h')
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH EXAMPLES
.TP
Show disk usage chart of current working directory
.nf
\fB$ pdu\fR
.fi
.TP
Show disk usage chart of a single file or directory
.nf
\fB$ pdu path/to/file/or/directory\fR
.fi
.TP
Compare disk usages of multiple files and/or directories
.nf
\fB$ pdu file.txt dir/\fR
.fi
.TP
Show chart in apparent sizes instead of block sizes
.nf
\fB$ pdu \-\-quantity=apparent\-size\fR
.fi
.TP
Detect and subtract the sizes of hardlinks from their parent nodes
.nf
\fB$ pdu \-\-deduplicate\-hardlinks\fR
.fi
.TP
Show sizes in plain numbers instead of metric units
.nf
\fB$ pdu \-\-bytes\-format=plain\fR
.fi
.TP
Show sizes in base 2¹⁰ units (binary) instead of base 10³ units (metric)
.nf
\fB$ pdu \-\-bytes\-format=binary\fR
.fi
.TP
Show disk usage chart of all entries regardless of size
.nf
\fB$ pdu \-\-min\-ratio=0\fR
.fi
.TP
Only show disk usage chart of entries whose size is at least 5% of total
.nf
\fB$ pdu \-\-min\-ratio=0.05\fR
.fi
.TP
Show disk usage data as JSON instead of chart
.nf
\fB$ pdu \-\-min\-ratio=0 \-\-max\-depth=inf \-\-json\-output | jq\fR
.fi
.TP
Visualize existing JSON representation of disk usage data
.nf
\fB$ pdu \-\-json\-input < disk\-usage.json\fR
.fi
.SH VERSION
v0.21.1
